feat: IndexedDB support
joshnuss/svelte-local-storage-store pull request #273
Opened 2024-06-09 09:15 UTC by intercepted16

Implement IndexedDB support, useful for storing larger amounts of data.

- The persisted function is now deprecated, but remains functional
- Instead of a storage option, there are now three seperate functions;
 localState, sessionState and indexedDBState
- The localState and sessionState functions remain the same, aside from the storage parameter
- indexedDBState is asynchronous and uses async/await (or callback)
- Some refactoring was done, specifically with types

**PS:** persisted() remains functional with the same API

2024-06-09 22:12 UTC, webJose requested changes
Generally speaking, and without reviewing every single change, I would say the change looks well done.  Since the entries are separated functions, this should tree-shake well as far as I know.  It would be ideal if tree-shaking tests could be added in order to verify that existing users won't get extra stuff in their bundles unnecessarily.

@joshnuss, do you have a roadmap as to when to get out of experimental versions?  I see you have kept the versions experimental for a long time.  What is the requirement to hit v1.0.0?  I ask because this PR looks like a good candidate to hit it.  Maybe you could also give this a round of release-candidate versions before becoming final (1.0.0-rc.1)?  If you agree, maybe it is also time to get rid of `writable()`?

2024-06-09 22:12 UTC, webJose commented on types/options.ts
> +}
It would be nice if descriptions in plain, well written and grammatically correct English were added to all types using JsDoc comments.  They will appear along with Intellisense and can be written in Markdown, leading to beautiful and helpful on-the-spot pieces of information.

As an example, see how I comment my types in this Svelte package:  https://github.com/WJSoftware/wjfe-single-spa-svelte/blob/main/src/lib/wjfe-single-spa-svelte.d.ts

2024-06-09 22:12 UTC, webJose commented on index.ts
> +    "writable() has been deprecated. Please use localState(()) instead.\n\nchange:\n\nimport { writable } from 'svelte-persisted-store-idb'\n\nto:\n\nimport { persisted } from 'svelte-persisted-store
```suggestion
    "writable() has been deprecated. Please use localState() instead.\n\nchange:\n\nimport { writable } from 'svelte-persisted-store-idb'\n\nto:\n\nimport { persisted } from 'svelte-persisted-store-idb'"
```

2024-06-10 00:35 UTC, intercepted16 commented on types/options.ts
> +}
@webJose I've added JSDoc types.

2024-06-10 00:36 UTC, intercepted16 commented on index.ts
> +    "writable() has been deprecated. Please use localState(()) instead.\n\nchange:\n\nimport { writable } from 'svelte-persisted-store-idb'\n\nto:\n\nimport { persisted } from 'svelte-persisted-store
I've fixed this and a few grammatical errors.

2024-06-10 01:21 UTC, intercepted16 commented
@webJose Your changes were small, so I figured implementing them wouldn't hurt.

2024-07-13 08:08 UTC, intercepted16 commented
@joshnuss Are you willing to add this feature? It's been a while with no response.

2024-07-16 01:43 UTC, joshnuss commented
Hi, I do t have a good answer right now.

The next priority for the project is adding support for runes, so I'm not sure we should add more features right now.

Is this an important requirement you're waiting on?

2024-07-16 05:35 UTC, intercepted16 commented
@joshnuss  Yes, I'd prefer to use the library for this; currently I'm using a custom solution. Maybe, as breaking changes are being implemented anyway, you could include this pull request in the runes change?

2024-10-06 23:14 UTC, plutonium-239 commented
I second (third) this PR/feature!

2025-02-27 07:57 UTC, intercepted16 commented
@joshnuss Still nothing?

2025-02-27 08:09 UTC, joshnuss commented
Sorry, can you clarify what the question is?

2025-02-27 08:22 UTC, intercepted16 commented
@joshnuss are you going to add it? Been 9 months since made, and you've updated it to svelte 5.

2025-02-27 08:26 UTC, joshnuss commented
The repo still need to be updated to Svelte Runes.
Once that happens we can consider whether to add new storage adapters. 

But I cannot promise anything, the API for indexed db and local/session storage are quite different and it might not make sense to fit them in the same API, research will have to be done, so no promises.

2025-06-07 09:38 UTC, intercepted16 commented
@joshnuss Has it been updated to Svelte Runes. this PR is almost a year old now!

2025-06-07 17:09 UTC, joshnuss commented
It hasn't been updated yet.

This project is updated on my free time, and is not sponsored work. So please refrain from placing pressure on me.

2025-06-08 02:59 UTC, intercepted16 commented
@joshnuss My bad, not trying to put pressure.

2025-12-23 11:30 UTC, closed without merging